apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: faithful-e2e-f
  namespace: colossus-faithful-e2e-f
  labels:
    app: faithful-e2e-f
    managed-by: colossus
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: ubuntu.desmana-truck.ts.net
      http:
        paths:
          - path: /faithful-e2e-f(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: faithful-e2e-f
                port:
                  number: 80
  tls:
    - hosts:
        - ubuntu.desmana-truck.ts.net
      secretName: colossus-shared-tls
